# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\G\Desktop\Python\yun\yun.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(497, 363)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-3, 260, 320, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Bt_yun_x = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bt_yun_x.setEnabled(True)
        self.Bt_yun_x.setObjectName("Bt_yun_x")
        self.gridLayout.addWidget(self.Bt_yun_x, 0, 0, 1, 1)
        self.Bt_bo_x = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bt_bo_x.setEnabled(False)
        self.Bt_bo_x.setObjectName("Bt_bo_x")
        self.gridLayout.addWidget(self.Bt_bo_x, 0, 1, 1, 1)
        self.Bt_xxdf = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bt_xxdf.setEnabled(False)
        self.Bt_xxdf.setObjectName("Bt_xxdf")
        self.gridLayout.addWidget(self.Bt_xxdf, 0, 3, 1, 1)
        self.Bt_dang_x = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bt_dang_x.setEnabled(False)
        self.Bt_dang_x.setObjectName("Bt_dang_x")
        self.gridLayout.addWidget(self.Bt_dang_x, 0, 2, 1, 1)
        self.Bt_yun_z = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bt_yun_z.setEnabled(False)
        self.Bt_yun_z.setObjectName("Bt_yun_z")
        self.gridLayout.addWidget(self.Bt_yun_z, 1, 0, 1, 1)
        self.Bt_bo_z = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bt_bo_z.setEnabled(False)
        self.Bt_bo_z.setObjectName("Bt_bo_z")
        self.gridLayout.addWidget(self.Bt_bo_z, 1, 1, 1, 1)
        self.Bt_dang_z = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bt_dang_z.setEnabled(False)
        self.Bt_dang_z.setObjectName("Bt_dang_z")
        self.gridLayout.addWidget(self.Bt_dang_z, 1, 2, 1, 1)
        self.Bt_xlfd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Bt_xlfd.setEnabled(False)
        self.Bt_xlfd.setObjectName("Bt_xlfd")
        self.gridLayout.addWidget(self.Bt_xlfd, 1, 3, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setGeometry(QtCore.QRect(-3, 20, 161, 211))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setDocumentTitle("")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_3.setGeometry(QtCore.QRect(317, 20, 181, 321))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_2.setGeometry(QtCore.QRect(157, 20, 161, 211))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(-3, 230, 161, 20))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(157, 230, 161, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 321, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(320, 0, 181, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 497, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionguanyu = QtWidgets.QAction(MainWindow)
        self.actionguanyu.setObjectName("actionguanyu")
        self.menu.addAction(self.actionguanyu)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "运"))
        self.Bt_yun_x.setText(_translate("MainWindow", "运"))
        self.Bt_bo_x.setText(_translate("MainWindow", "小波"))
        self.Bt_xxdf.setText(_translate("MainWindow", "吸星大法"))
        self.Bt_dang_x.setText(_translate("MainWindow", "小挡"))
        self.Bt_yun_z.setText(_translate("MainWindow", "中运"))
        self.Bt_bo_z.setText(_translate("MainWindow", "中波"))
        self.Bt_dang_z.setText(_translate("MainWindow", "中挡"))
        self.Bt_xlfd.setText(_translate("MainWindow", "小李飞刀"))
        self.label.setText(_translate("MainWindow", "对手状态"))
        self.label_2.setText(_translate("MainWindow", "你的状态"))
        self.label_3.setText(_translate("MainWindow", "对手"))
        self.label_4.setText(_translate("MainWindow", "信息"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionguanyu.setText(_translate("MainWindow", "guanyu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

